### ISSUE TITLE
Display formatter: Display label source preferred order setting not sticking

### ISSUE THREAD

**Issue by kspurgin** [lyrasis/typed_labeled_fields#2]
## To reproduce:

- Spin up ISLE-DC instance and enable this module
- [Add new field](https://islandora.traefik.me/admin/structure/types/manage/islandora_object/fields/add-field) (field_testfield) with field type = Typed Labeled Text (plain)

![image](https://user-images.githubusercontent.com/450570/148831678-fb97025b-ec4c-4f2e-bdff-f62f97341499.png)

- Set Allowed number of values to Unlimited

![image](https://user-images.githubusercontent.com/450570/148831819-82d0c005-69e0-4b14-8e14-2c1e1110f747.png)

- Set Type Reference Settings to pull from Islandora Models vocabulary (for testing only, since that one is populated out of the box)

![image](https://user-images.githubusercontent.com/450570/148832038-4f3baab5-ce03-4298-b467-5d6433c98cbb.png)

- Enable field_testfield in [Manage form display](https://islandora.traefik.me/admin/structure/types/manage/islandora_object/form-display) and SAVE
- Enable field_testfield in [Manage display](https://islandora.traefik.me/admin/structure/types/manage/islandora_object/display) and SAVE
- Still in Manage display, click settings gear at right for field_testfield

- Under DISPLAY LABEL SOURCE PREFERRED ORDER, drag the "Prefer the fields "Label value" when present" option to under "Ignore"

![image](https://user-images.githubusercontent.com/450570/148832811-0ebbb574-35e5-46bc-8f4d-913f014ac3c5.png)

- Click "Update" then "Save" on the overall page
- Re-click the settings gear at right for field_testfield
- You should see "Prefer the fields "Label value" when present" back in the preferred order list, with no options ignored.

# Effect

I'm stuck with this in the Entity view display / node.islandora_object.default config: 

```
  field_testfield:
    weight: 2
    label: above
    settings:
      display_label_source:
        - type
        - field
        - label
```

I'm able to use the "Manage display" form in ECS to change the display on a field of the same field type to ([in repo](https://github.com/lyrasis/ecs/blob/metadata-config-with-fields/docker/lyrasis-drupal/drupal/config/sync/core.entity_view_display.node.lyrasis_repository_item.default.yml#L152-L158): 

```
 field_identifier:
    weight: 4
    label: above
    settings:
      display_label_source:
        - type
        - field
```
